**Healthcare cleaning**

My objective is to clean the dataset so it can be used for visualzations

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Here I have imported all the languages I will need. If I need to import anymore, I will import them under this cell, but above the cleaning.

In [2]:
df = pd.read_csv('../Datasets/healthcare_dataset.csv')

In [3]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

Here I have imported the dataframe I will work on.

In [4]:
df = df[:10000]

Here I have dropped it to the top 10,000 rows so that I am working with a smaller dataset

In [5]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David JoNEs,51,Female,O-,Arthritis,2019-09-25,Isaac Silva,Rice and Sons,Cigna,5127.438142,106,Urgent,2019-10-03,Ibuprofen,Normal
9996,NICOle BRooKS,61,Male,B-,Diabetes,2020-06-03,Jose Cohen,"Johnson, Adkins and Ferguson",Aetna,47855.349591,122,Emergency,2020-06-04,Paracetamol,Normal
9997,MIKE TayloR,25,Male,B-,Cancer,2024-03-14,Michael Hess,Kramer-Hogan,UnitedHealthcare,40787.180500,440,Elective,2024-03-28,Penicillin,Inconclusive
9998,ReBeccA ramos ddS,71,Male,A-,Hypertension,2023-08-22,Cheryl Faulkner,"Williams Barnes and Fletcher,",Blue Cross,25979.751629,319,Emergency,2023-09-03,Lipitor,Inconclusive
9999,rebeCCA stEPHenSOn,24,Male,A+,Hypertension,2023-04-24,Jonathan Owens,Jones Ltd,Cigna,19782.638991,438,Emergency,2023-05-23,Ibuprofen,Inconclusive

Here I have checked to see that my sampling of the dataset worked

In [6]:
df.isna().any()

Name                  False
Age                   False
Gender                False
Blood Type            False
Medical Condition     False
Date of Admission     False
Doctor                False
Hospital              False
Insurance Provider    False
Billing Amount        False
Room Number           False
Admission Type        False
Discharge Date        False
Medication            False
Test Results          False
dtype: bool

Here I have checked for any null cells in the data

In [7]:
duplicates = df.duplicated()
print("number of duplicate rows: ", duplicates.sum())

df[duplicates]

number of duplicate rows:  0

Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

Here is says that there is no dupliacted rows within the dataset. Although this maybe true here, by sorting the names alphabetically, I found duplicated rows, with differing ages. At the moment I will leave it, but may come back to this later, when I know what to do properly.

In [8]:
df["Age Range"] = np.nan
df["Patient ID"] = np.nan
df.drop(columns=["Gender", "Room Number", ], inplace=True)

C:\Users\matte\AppData\Local\Temp\ipykernel_33788\2674994778.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age Range"] = np.nan
C:\Users\matte\AppData\Local\Temp\ipykernel_33788\2674994778.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Patient ID"] = np.nan
C:\Users\matte\AppData\Local\Temp\ipykernel_33788\2674994778.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["Gender", "Room Number", ], inplace=True)

In [9]:
df

,Name,Age,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results,Age Range,Patient ID
0,Bobby JacksOn,30,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal,NaN,NaN
1,LesLie TErRy,62,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive,NaN,NaN
2,DaNnY sMitH,76,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal,NaN,NaN
3,andrEw waTtS,28,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal,NaN,NaN
4,adrIENNE bEll,43,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David JoNEs,51,O-,Arthritis,2019-09-25,Isaac Silva,Rice and Sons,Cigna,5127.438142,Urgent,2019-10-03,Ibuprofen,Normal,NaN,NaN
9996,NICOle BRooKS,61,B-,Diabetes,2020-06-03,Jose Cohen,"Johnson, Adkins and Ferguson",Aetna,47855.349591,Emergency,2020-06-04,Paracetamol,Normal,NaN,NaN
9997,MIKE TayloR,25,B-,Cancer,2024-03-14,Michael Hess,Kramer-Hogan,UnitedHealthcare,40787.180500,Elective,2024-03-28,Penicillin,Inconclusive,NaN,NaN
9998,ReBeccA ramos ddS,71,A-,Hypertension,2023-08-22,Cheryl Faulkner,"Williams Barnes and Fletcher,",Blue Cross,25979.751629,Emergency,2023-09-03,Lipitor,Inconclusive,NaN,NaN
9999,rebeCCA stEPHenSOn,24,A+,Hypertension,2023-04-24,Jonathan Owens,Jones Ltd,Cigna,19782.638991,Emergency,2023-05-23,Ibuprofen,Inconclusive,NaN,NaN