**Healthcare cleaning**

My objective is to clean the dataset so it can be used for visualzations.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Here I have imported all the languages I will need. If I need to import anymore, I will import them under this cell, but above the cleaning.

In [2]:
import random
import base64
from IPython.display import HTML
import io
from sklearn.linear_model import LinearRegression

"import random" was used to randomly assign patients ID numbers.
"import base64" was used to get the downloadable files of the cleaned data for both CSV and XLSX.
"import IPython.display" was used to get the downloadable files of the cleaned data for both CSV and XLSX.
"import io" was used to get the downloadable file of the cleaned data for XLSX.

In [3]:
df = pd.read_csv('../Datasets/healthcare_dataset.csv')

In [4]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

Here I have imported the dataframe I will work on.

In [5]:
df = df[:10000]

Here I have dropped it to the top 10,000 rows so that I am working with a smaller dataset. The later visualisations will be affected by the smaller size of the dataset. This may cause an anomalies within the dataset to standout more with the visualisatons.

In [6]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David JoNEs,51,Female,O-,Arthritis,2019-09-25,Isaac Silva,Rice and Sons,Cigna,5127.438142,106,Urgent,2019-10-03,Ibuprofen,Normal
9996,NICOle BRooKS,61,Male,B-,Diabetes,2020-06-03,Jose Cohen,"Johnson, Adkins and Ferguson",Aetna,47855.349591,122,Emergency,2020-06-04,Paracetamol,Normal
9997,MIKE TayloR,25,Male,B-,Cancer,2024-03-14,Michael Hess,Kramer-Hogan,UnitedHealthcare,40787.180500,440,Elective,2024-03-28,Penicillin,Inconclusive
9998,ReBeccA ramos ddS,71,Male,A-,Hypertension,2023-08-22,Cheryl Faulkner,"Williams Barnes and Fletcher,",Blue Cross,25979.751629,319,Emergency,2023-09-03,Lipitor,Inconclusive
9999,rebeCCA stEPHenSOn,24,Male,A+,Hypertension,2023-04-24,Jonathan Owens,Jones Ltd,Cigna,19782.638991,438,Emergency,2023-05-23,Ibuprofen,Inconclusive

Here I have checked to see that my sampling of the dataset worked.

In [7]:
df.isna().any()

Name                  False
Age                   False
Gender                False
Blood Type            False
Medical Condition     False
Date of Admission     False
Doctor                False
Hospital              False
Insurance Provider    False
Billing Amount        False
Room Number           False
Admission Type        False
Discharge Date        False
Medication            False
Test Results          False
dtype: bool

Here I have checked for any null cells in the data.

In [8]:
duplicates = df.duplicated()
print("number of duplicate rows: ", duplicates.sum())

df[duplicates]

number of duplicate rows:  0

Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

Here is says that there is no dupliacted rows within the dataset. Although this maybe true here, by sorting the names alphabetically, I found duplicated rows, with differing ages. At the moment I will leave it, but may come back to this later, when I know what to do properly.

In [9]:
df["Age Range"] = np.nan
df["Patient ID"] = np.nan
df.drop(columns=["Gender"], inplace=True)

C:\Users\matte\AppData\Local\Temp\ipykernel_22384\1068108559.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age Range"] = np.nan
C:\Users\matte\AppData\Local\Temp\ipykernel_22384\1068108559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Patient ID"] = np.nan
C:\Users\matte\AppData\Local\Temp\ipykernel_22384\1068108559.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["Gender"], inplace=True)

In [10]:
df

,Name,Age,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Age Range,Patient ID
0,Bobby JacksOn,30,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,NaN,NaN
1,LesLie TErRy,62,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,NaN,NaN
2,DaNnY sMitH,76,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,NaN,NaN
3,andrEw waTtS,28,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,NaN,NaN
4,adrIENNE bEll,43,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David JoNEs,51,O-,Arthritis,2019-09-25,Isaac Silva,Rice and Sons,Cigna,5127.438142,106,Urgent,2019-10-03,Ibuprofen,Normal,NaN,NaN
9996,NICOle BRooKS,61,B-,Diabetes,2020-06-03,Jose Cohen,"Johnson, Adkins and Ferguson",Aetna,47855.349591,122,Emergency,2020-06-04,Paracetamol,Normal,NaN,NaN
9997,MIKE TayloR,25,B-,Cancer,2024-03-14,Michael Hess,Kramer-Hogan,UnitedHealthcare,40787.180500,440,Elective,2024-03-28,Penicillin,Inconclusive,NaN,NaN
9998,ReBeccA ramos ddS,71,A-,Hypertension,2023-08-22,Cheryl Faulkner,"Williams Barnes and Fletcher,",Blue Cross,25979.751629,319,Emergency,2023-09-03,Lipitor,Inconclusive,NaN,NaN
9999,rebeCCA stEPHenSOn,24,A+,Hypertension,2023-04-24,Jonathan Owens,Jones Ltd,Cigna,19782.638991,438,Emergency,2023-05-23,Ibuprofen,Inconclusive,NaN,NaN

Here, I have added Age Range, this will allow me to use box plots, and bar graphs better, as there will be a higher collection in the age range over the smaller collection of individual ages. I have also added a Patient ID, this is so that later on I can remove the names column from the dataset, for ethics reasons. I have elected to remove Gender for ethics reasons, the main reason I dropped the gender column was because I couldn't work out a way to make sure it was properly sorted, ideally I would be able to clean it if I had access to all the patients information. I had also planned to drop the Room Number column as it was not going to be used for visualisations, but if this had to be given to more people, especially doctors, it was information that would be linked to their patient ID.

In [11]:
df = df.iloc[:10000].copy()
to_drop = []
for idx, age in df["Age"].items():
    if age < 18:
        to_drop.append(idx)
    elif 18 <= age < 30:
        df.loc[idx, "Age Range"] = "18-29"
    elif 30 <= age < 45:
        df.loc[idx, "Age Range"] = "30-44"
    elif 45 <= age < 60:
        df.loc[idx, "Age Range"] = "45-59"
    elif 60 <= age < 75:
        df.loc[idx, "Age Range"] = "60-74"
    else:
        df.loc[idx, "Age Range"] = "75+"
df.drop(index=to_drop, inplace=True)

C:\Users\matte\AppData\Local\Temp\ipykernel_22384\2246197444.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '30-44' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, "Age Range"] = "30-44"

Here I have made an if statement to drop each person under the age of 18, and add age ranges for everyone over 18. The reason I have dropped everyone who was under the age of 18 was for ethical reasons.

In [12]:
df

,Name,Age,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Age Range,Patient ID
0,Bobby JacksOn,30,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,30-44,NaN
1,LesLie TErRy,62,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,60-74,NaN
2,DaNnY sMitH,76,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,75+,NaN
3,andrEw waTtS,28,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,18-29,NaN
4,adrIENNE bEll,43,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,30-44,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David JoNEs,51,O-,Arthritis,2019-09-25,Isaac Silva,Rice and Sons,Cigna,5127.438142,106,Urgent,2019-10-03,Ibuprofen,Normal,45-59,NaN
9996,NICOle BRooKS,61,B-,Diabetes,2020-06-03,Jose Cohen,"Johnson, Adkins and Ferguson",Aetna,47855.349591,122,Emergency,2020-06-04,Paracetamol,Normal,60-74,NaN
9997,MIKE TayloR,25,B-,Cancer,2024-03-14,Michael Hess,Kramer-Hogan,UnitedHealthcare,40787.180500,440,Elective,2024-03-28,Penicillin,Inconclusive,18-29,NaN
9998,ReBeccA ramos ddS,71,A-,Hypertension,2023-08-22,Cheryl Faulkner,"Williams Barnes and Fletcher,",Blue Cross,25979.751629,319,Emergency,2023-09-03,Lipitor,Inconclusive,60-74,NaN
9999,rebeCCA stEPHenSOn,24,A+,Hypertension,2023-04-24,Jonathan Owens,Jones Ltd,Cigna,19782.638991,438,Emergency,2023-05-23,Ibuprofen,Inconclusive,18-29,NaN

In [13]:
to_drop = []
df = df.iloc[:10000].copy()
to_drop = []
for idx, val in df["Billing Amount"].items():
    if idx < 0:
       to_drop.append(idx)

In [14]:
df

,Name,Age,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Age Range,Patient ID
0,Bobby JacksOn,30,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,30-44,NaN
1,LesLie TErRy,62,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,60-74,NaN
2,DaNnY sMitH,76,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,75+,NaN
3,andrEw waTtS,28,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,18-29,NaN
4,adrIENNE bEll,43,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,30-44,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David JoNEs,51,O-,Arthritis,2019-09-25,Isaac Silva,Rice and Sons,Cigna,5127.438142,106,Urgent,2019-10-03,Ibuprofen,Normal,45-59,NaN
9996,NICOle BRooKS,61,B-,Diabetes,2020-06-03,Jose Cohen,"Johnson, Adkins and Ferguson",Aetna,47855.349591,122,Emergency,2020-06-04,Paracetamol,Normal,60-74,NaN
9997,MIKE TayloR,25,B-,Cancer,2024-03-14,Michael Hess,Kramer-Hogan,UnitedHealthcare,40787.180500,440,Elective,2024-03-28,Penicillin,Inconclusive,18-29,NaN
9998,ReBeccA ramos ddS,71,A-,Hypertension,2023-08-22,Cheryl Faulkner,"Williams Barnes and Fletcher,",Blue Cross,25979.751629,319,Emergency,2023-09-03,Lipitor,Inconclusive,60-74,NaN
9999,rebeCCA stEPHenSOn,24,A+,Hypertension,2023-04-24,Jonathan Owens,Jones Ltd,Cigna,19782.638991,438,Emergency,2023-05-23,Ibuprofen,Inconclusive,18-29,NaN

In [15]:
df = df[["Name", "Patient ID", "Age", "Age Range", "Blood Type", "Medical Condition", "Date of Admission", "Discharge Date", "Billing Amount", "Doctor", "Hospital", "Room Number", "Insurance Provider", "Medication", "Test Results", "Admission Type", ]]

In [16]:
df

,Name,Patient ID,Age,Age Range,Blood Type,Medical Condition,Date of Admission,Discharge Date,Billing Amount,Doctor,Hospital,Room Number,Insurance Provider,Medication,Test Results,Admission Type
0,Bobby JacksOn,NaN,30,30-44,B-,Cancer,2024-01-31,2024-02-02,18856.281306,Matthew Smith,Sons and Miller,328,Blue Cross,Paracetamol,Normal,Urgent
1,LesLie TErRy,NaN,62,60-74,A+,Obesity,2019-08-20,2019-08-26,33643.327287,Samantha Davies,Kim Inc,265,Medicare,Ibuprofen,Inconclusive,Emergency
2,DaNnY sMitH,NaN,76,75+,A-,Obesity,2022-09-22,2022-10-07,27955.096079,Tiffany Mitchell,Cook PLC,205,Aetna,Aspirin,Normal,Emergency
3,andrEw waTtS,NaN,28,18-29,O+,Diabetes,2020-11-18,2020-12-18,37909.782410,Kevin Wells,"Hernandez Rogers and Vang,",450,Medicare,Ibuprofen,Abnormal,Elective
4,adrIENNE bEll,NaN,43,30-44,AB+,Cancer,2022-09-19,2022-10-09,14238.317814,Kathleen Hanna,White-White,458,Aetna,Penicillin,Abnormal,Urgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David JoNEs,NaN,51,45-59,O-,Arthritis,2019-09-25,2019-10-03,5127.438142,Isaac Silva,Rice and Sons,106,Cigna,Ibuprofen,Normal,Urgent
9996,NICOle BRooKS,NaN,61,60-74,B-,Diabetes,2020-06-03,2020-06-04,47855.349591,Jose Cohen,"Johnson, Adkins and Ferguson",122,Aetna,Paracetamol,Normal,Emergency
9997,MIKE TayloR,NaN,25,18-29,B-,Cancer,2024-03-14,2024-03-28,40787.180500,Michael Hess,Kramer-Hogan,440,UnitedHealthcare,Penicillin,Inconclusive,Elective
9998,ReBeccA ramos ddS,NaN,71,60-74,A-,Hypertension,2023-08-22,2023-09-03,25979.751629,Cheryl Faulkner,"Williams Barnes and Fletcher,",319,Blue Cross,Lipitor,Inconclusive,Emergency
9999,rebeCCA stEPHenSOn,NaN,24,18-29,A+,Hypertension,2023-04-24,2023-05-23,19782.638991,Jonathan Owens,Jones Ltd,438,Cigna,Ibuprofen,Inconclusive,Emergency

Here I have organised the columns in the data frame, to make it easier to read.

In [17]:
df['Name'] = df['Name'].str.lower()

In [18]:
df

,Name,Patient ID,Age,Age Range,Blood Type,Medical Condition,Date of Admission,Discharge Date,Billing Amount,Doctor,Hospital,Room Number,Insurance Provider,Medication,Test Results,Admission Type
0,bobby jackson,NaN,30,30-44,B-,Cancer,2024-01-31,2024-02-02,18856.281306,Matthew Smith,Sons and Miller,328,Blue Cross,Paracetamol,Normal,Urgent
1,leslie terry,NaN,62,60-74,A+,Obesity,2019-08-20,2019-08-26,33643.327287,Samantha Davies,Kim Inc,265,Medicare,Ibuprofen,Inconclusive,Emergency
2,danny smith,NaN,76,75+,A-,Obesity,2022-09-22,2022-10-07,27955.096079,Tiffany Mitchell,Cook PLC,205,Aetna,Aspirin,Normal,Emergency
3,andrew watts,NaN,28,18-29,O+,Diabetes,2020-11-18,2020-12-18,37909.782410,Kevin Wells,"Hernandez Rogers and Vang,",450,Medicare,Ibuprofen,Abnormal,Elective
4,adrienne bell,NaN,43,30-44,AB+,Cancer,2022-09-19,2022-10-09,14238.317814,Kathleen Hanna,White-White,458,Aetna,Penicillin,Abnormal,Urgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,david jones,NaN,51,45-59,O-,Arthritis,2019-09-25,2019-10-03,5127.438142,Isaac Silva,Rice and Sons,106,Cigna,Ibuprofen,Normal,Urgent
9996,nicole brooks,NaN,61,60-74,B-,Diabetes,2020-06-03,2020-06-04,47855.349591,Jose Cohen,"Johnson, Adkins and Ferguson",122,Aetna,Paracetamol,Normal,Emergency
9997,mike taylor,NaN,25,18-29,B-,Cancer,2024-03-14,2024-03-28,40787.180500,Michael Hess,Kramer-Hogan,440,UnitedHealthcare,Penicillin,Inconclusive,Elective
9998,rebecca ramos dds,NaN,71,60-74,A-,Hypertension,2023-08-22,2023-09-03,25979.751629,Cheryl Faulkner,"Williams Barnes and Fletcher,",319,Blue Cross,Lipitor,Inconclusive,Emergency
9999,rebecca stephenson,NaN,24,18-29,A+,Hypertension,2023-04-24,2023-05-23,19782.638991,Jonathan Owens,Jones Ltd,438,Cigna,Ibuprofen,Inconclusive,Emergency

In [19]:
df["Name"] = df["Name"].str.title()

In [20]:
df

,Name,Patient ID,Age,Age Range,Blood Type,Medical Condition,Date of Admission,Discharge Date,Billing Amount,Doctor,Hospital,Room Number,Insurance Provider,Medication,Test Results,Admission Type
0,Bobby Jackson,NaN,30,30-44,B-,Cancer,2024-01-31,2024-02-02,18856.281306,Matthew Smith,Sons and Miller,328,Blue Cross,Paracetamol,Normal,Urgent
1,Leslie Terry,NaN,62,60-74,A+,Obesity,2019-08-20,2019-08-26,33643.327287,Samantha Davies,Kim Inc,265,Medicare,Ibuprofen,Inconclusive,Emergency
2,Danny Smith,NaN,76,75+,A-,Obesity,2022-09-22,2022-10-07,27955.096079,Tiffany Mitchell,Cook PLC,205,Aetna,Aspirin,Normal,Emergency
3,Andrew Watts,NaN,28,18-29,O+,Diabetes,2020-11-18,2020-12-18,37909.782410,Kevin Wells,"Hernandez Rogers and Vang,",450,Medicare,Ibuprofen,Abnormal,Elective
4,Adrienne Bell,NaN,43,30-44,AB+,Cancer,2022-09-19,2022-10-09,14238.317814,Kathleen Hanna,White-White,458,Aetna,Penicillin,Abnormal,Urgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David Jones,NaN,51,45-59,O-,Arthritis,2019-09-25,2019-10-03,5127.438142,Isaac Silva,Rice and Sons,106,Cigna,Ibuprofen,Normal,Urgent
9996,Nicole Brooks,NaN,61,60-74,B-,Diabetes,2020-06-03,2020-06-04,47855.349591,Jose Cohen,"Johnson, Adkins and Ferguson",122,Aetna,Paracetamol,Normal,Emergency
9997,Mike Taylor,NaN,25,18-29,B-,Cancer,2024-03-14,2024-03-28,40787.180500,Michael Hess,Kramer-Hogan,440,UnitedHealthcare,Penicillin,Inconclusive,Elective
9998,Rebecca Ramos Dds,NaN,71,60-74,A-,Hypertension,2023-08-22,2023-09-03,25979.751629,Cheryl Faulkner,"Williams Barnes and Fletcher,",319,Blue Cross,Lipitor,Inconclusive,Emergency
9999,Rebecca Stephenson,NaN,24,18-29,A+,Hypertension,2023-04-24,2023-05-23,19782.638991,Jonathan Owens,Jones Ltd,438,Cigna,Ibuprofen,Inconclusive,Emergency

Here I have lowered the case for the names, then titled them, so they fit the same capitalizations.

In [21]:
for i in df.index:
    pid = random.randint(1_000_000_000, 10_000_000_000)
    df.loc[i, "Patient ID"] = str(pid)

C:\Users\matte\AppData\Local\Temp\ipykernel_22384\1242190293.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3991193750' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, "Patient ID"] = str(pid)

In [22]:
df

,Name,Patient ID,Age,Age Range,Blood Type,Medical Condition,Date of Admission,Discharge Date,Billing Amount,Doctor,Hospital,Room Number,Insurance Provider,Medication,Test Results,Admission Type
0,Bobby Jackson,3991193750,30,30-44,B-,Cancer,2024-01-31,2024-02-02,18856.281306,Matthew Smith,Sons and Miller,328,Blue Cross,Paracetamol,Normal,Urgent
1,Leslie Terry,2871882881,62,60-74,A+,Obesity,2019-08-20,2019-08-26,33643.327287,Samantha Davies,Kim Inc,265,Medicare,Ibuprofen,Inconclusive,Emergency
2,Danny Smith,5993728845,76,75+,A-,Obesity,2022-09-22,2022-10-07,27955.096079,Tiffany Mitchell,Cook PLC,205,Aetna,Aspirin,Normal,Emergency
3,Andrew Watts,3841712627,28,18-29,O+,Diabetes,2020-11-18,2020-12-18,37909.782410,Kevin Wells,"Hernandez Rogers and Vang,",450,Medicare,Ibuprofen,Abnormal,Elective
4,Adrienne Bell,8123012669,43,30-44,AB+,Cancer,2022-09-19,2022-10-09,14238.317814,Kathleen Hanna,White-White,458,Aetna,Penicillin,Abnormal,Urgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David Jones,8152487175,51,45-59,O-,Arthritis,2019-09-25,2019-10-03,5127.438142,Isaac Silva,Rice and Sons,106,Cigna,Ibuprofen,Normal,Urgent
9996,Nicole Brooks,1769176082,61,60-74,B-,Diabetes,2020-06-03,2020-06-04,47855.349591,Jose Cohen,"Johnson, Adkins and Ferguson",122,Aetna,Paracetamol,Normal,Emergency
9997,Mike Taylor,1874421903,25,18-29,B-,Cancer,2024-03-14,2024-03-28,40787.180500,Michael Hess,Kramer-Hogan,440,UnitedHealthcare,Penicillin,Inconclusive,Elective
9998,Rebecca Ramos Dds,9527910327,71,60-74,A-,Hypertension,2023-08-22,2023-09-03,25979.751629,Cheryl Faulkner,"Williams Barnes and Fletcher,",319,Blue Cross,Lipitor,Inconclusive,Emergency
9999,Rebecca Stephenson,6360866489,24,18-29,A+,Hypertension,2023-04-24,2023-05-23,19782.638991,Jonathan Owens,Jones Ltd,438,Cigna,Ibuprofen,Inconclusive,Emergency

Here I have added a random 10 digit number as a patient ID, so I can delete the names for ethics reasons. I plan to make some code to allow me to check to see if the Patient ID column has any duplicates in it and rerun the code if it does.

In [23]:
df["Billing Amount"] = df["Billing Amount"].round(2)

In [24]:
df

,Name,Patient ID,Age,Age Range,Blood Type,Medical Condition,Date of Admission,Discharge Date,Billing Amount,Doctor,Hospital,Room Number,Insurance Provider,Medication,Test Results,Admission Type
0,Bobby Jackson,3991193750,30,30-44,B-,Cancer,2024-01-31,2024-02-02,18856.28,Matthew Smith,Sons and Miller,328,Blue Cross,Paracetamol,Normal,Urgent
1,Leslie Terry,2871882881,62,60-74,A+,Obesity,2019-08-20,2019-08-26,33643.33,Samantha Davies,Kim Inc,265,Medicare,Ibuprofen,Inconclusive,Emergency
2,Danny Smith,5993728845,76,75+,A-,Obesity,2022-09-22,2022-10-07,27955.10,Tiffany Mitchell,Cook PLC,205,Aetna,Aspirin,Normal,Emergency
3,Andrew Watts,3841712627,28,18-29,O+,Diabetes,2020-11-18,2020-12-18,37909.78,Kevin Wells,"Hernandez Rogers and Vang,",450,Medicare,Ibuprofen,Abnormal,Elective
4,Adrienne Bell,8123012669,43,30-44,AB+,Cancer,2022-09-19,2022-10-09,14238.32,Kathleen Hanna,White-White,458,Aetna,Penicillin,Abnormal,Urgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,David Jones,8152487175,51,45-59,O-,Arthritis,2019-09-25,2019-10-03,5127.44,Isaac Silva,Rice and Sons,106,Cigna,Ibuprofen,Normal,Urgent
9996,Nicole Brooks,1769176082,61,60-74,B-,Diabetes,2020-06-03,2020-06-04,47855.35,Jose Cohen,"Johnson, Adkins and Ferguson",122,Aetna,Paracetamol,Normal,Emergency
9997,Mike Taylor,1874421903,25,18-29,B-,Cancer,2024-03-14,2024-03-28,40787.18,Michael Hess,Kramer-Hogan,440,UnitedHealthcare,Penicillin,Inconclusive,Elective
9998,Rebecca Ramos Dds,9527910327,71,60-74,A-,Hypertension,2023-08-22,2023-09-03,25979.75,Cheryl Faulkner,"Williams Barnes and Fletcher,",319,Blue Cross,Lipitor,Inconclusive,Emergency
9999,Rebecca Stephenson,6360866489,24,18-29,A+,Hypertension,2023-04-24,2023-05-23,19782.64,Jonathan Owens,Jones Ltd,438,Cigna,Ibuprofen,Inconclusive,Emergency

Here I have rounded the billing amount to 2 decimal places to fit most currencies in the world. Will change if needed later.

In [25]:
df.drop(columns=["Name"], inplace=True)

In [26]:
df

,Patient ID,Age,Age Range,Blood Type,Medical Condition,Date of Admission,Discharge Date,Billing Amount,Doctor,Hospital,Room Number,Insurance Provider,Medication,Test Results,Admission Type
0,3991193750,30,30-44,B-,Cancer,2024-01-31,2024-02-02,18856.28,Matthew Smith,Sons and Miller,328,Blue Cross,Paracetamol,Normal,Urgent
1,2871882881,62,60-74,A+,Obesity,2019-08-20,2019-08-26,33643.33,Samantha Davies,Kim Inc,265,Medicare,Ibuprofen,Inconclusive,Emergency
2,5993728845,76,75+,A-,Obesity,2022-09-22,2022-10-07,27955.10,Tiffany Mitchell,Cook PLC,205,Aetna,Aspirin,Normal,Emergency
3,3841712627,28,18-29,O+,Diabetes,2020-11-18,2020-12-18,37909.78,Kevin Wells,"Hernandez Rogers and Vang,",450,Medicare,Ibuprofen,Abnormal,Elective
4,8123012669,43,30-44,AB+,Cancer,2022-09-19,2022-10-09,14238.32,Kathleen Hanna,White-White,458,Aetna,Penicillin,Abnormal,Urgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8152487175,51,45-59,O-,Arthritis,2019-09-25,2019-10-03,5127.44,Isaac Silva,Rice and Sons,106,Cigna,Ibuprofen,Normal,Urgent
9996,1769176082,61,60-74,B-,Diabetes,2020-06-03,2020-06-04,47855.35,Jose Cohen,"Johnson, Adkins and Ferguson",122,Aetna,Paracetamol,Normal,Emergency
9997,1874421903,25,18-29,B-,Cancer,2024-03-14,2024-03-28,40787.18,Michael Hess,Kramer-Hogan,440,UnitedHealthcare,Penicillin,Inconclusive,Elective
9998,9527910327,71,60-74,A-,Hypertension,2023-08-22,2023-09-03,25979.75,Cheryl Faulkner,"Williams Barnes and Fletcher,",319,Blue Cross,Lipitor,Inconclusive,Emergency
9999,6360866489,24,18-29,A+,Hypertension,2023-04-24,2023-05-23,19782.64,Jonathan Owens,Jones Ltd,438,Cigna,Ibuprofen,Inconclusive,Emergency

Here I have dropped the names for ethics reasons.
1) The names are not important to visualisations
2) Becuase others may access the dataset, anonamyising the names with the 10 digit number means that less is likely to be breached

In [27]:
def create_download_link(df, title="healthcare_cleaned.csv", filename="healthcare_cleaned.csv"):
    """Generates a link to download the data in a given pandas DataFrame"""
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload, title=title, filename=filename)
    return HTML(html)
create_download_link(df)

In [28]:
def create_download_link_xlsx(df, title="healthcare_cleaned.xlsx", filename="healthcare_cleaned.xlsx"):
    """Generates a link to download the data in a given pandas DataFrame as XLSX"""
    towrite = io.BytesIO()
    df.to_excel(towrite, index=False)
    towrite.seek(0)
    b64 = base64.b64encode(towrite.read()).decode()
    html = f'<a download="{filename}" href="data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{b64}" target="_blank">{title}</a>'
    return HTML(html)
create_download_link_xlsx(df)

Here are downloadable copies of the dataset, this allows me to access it in Power Bi and another notebook a lot easier. I was having an issue with the code, so I asked ChatGPT what the problem was, and it was that I had forgotten to import the libraries when adding in this code

In [29]:
df["Billing Amount"].median()

np.float64(25633.06)

Here is the median cost we are billing the patients

In [30]:
df["Billing Amount"].mode()[0]

np.float64(2106.39)

Here is the mode of the billing amount

In [31]:
start = df["Date of Admission"].min()
end = df["Discharge Date"].max()
print("Date range from", start, "to", end)

Date range from 2019-05-08 to 2024-06-02

Here is the total range from the earliest patient entery, to the last patient leaving

In [32]:
std = df["Billing Amount"].std()
print("Standard Deviation of Billing Amount:", std)

Standard Deviation of Billing Amount: 14187.175237645011

Here is the standard deviation for the billing amount

In [33]:
start = df["Billing Amount"].min()
end = df["Billing Amount"].max()
print("Billing Amount ranges from", start, "to", end)

Billing Amount ranges from -1310.27 to 52271.66

Here is the range for the billing amount

In [34]:
# Convert dates to numeric values (days since epoch)
df['Date_Numeric'] = pd.to_datetime(df['Date of Admission']).astype(np.int64) // 10**9

# Prepare data in correct shape
X = df['Date_Numeric'].values.reshape(-1, 1)  # 2D array for features
y = df['Billing Amount'].values  # 1D array for target

# Fit model
model = LinearRegression()
model.fit(X, y)

# Prepare prediction date
x_predict = pd.to_datetime(['2024-01-31']).astype(np.int64) // 10**9
x_predict = np.array(x_predict).reshape(-1, 1)  # Convert to numpy array before reshaping

# Make prediction
y_predict = model.predict(x_predict)
print(f"Predicted billing amount for 2024-01-31: ${y_predict[0]:.2f}")

Predicted billing amount for 2024-01-31: $25457.11

In [35]:
#X = df.iloc[:, :-1].values
#Y = df.iloc[:, -1].values

#X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=1/3, random_state=42)
#regressorObject=LinearRegression()
#regressorObject.fit(X_train,Y_train)
#y_pred=regressorObject.predict(X_test)

#plt.scatter(X_test, Y_test, color='gray')